applicant_name: jeff_mcentarffer
applicant_email: jmcentarffer13@gmail.com

cover_letter_template: "templates/cover_letter.html"
cover_letter_context:
  greeting: "Hello Hiring Team,"
  opening: "I’m excited to apply for the {{ job_title }} role at {{ company }}."
  closing: "Thank you for your consideration,\n\nJeff_McEntarffer"

skills:
  - Python
  - Remote
  - Selenium
  - Automation

threshold: 0.75

resume_template: "templates/resume_template.docx"
resume_path: "output/jeff_mcentarffer_resume.pdf"
cover_letter_path: "output/jeff_mcentarffer_CL.pdf"
