# ────────────────────────────────────────────
# Personal Info (used by generate_application.py)
applicant_name: Jeff_McEntarffer
applicant_email: jeff@example.com

# ────────────────────────────────────────────
# Cover‐letter Template (Jinja HTML) & Context
cover_letter_template: "templates/cover_letter.html"
cover_letter_context:
  greeting: "Hello Hiring Team,"
  opening: "I’m thrilled to apply for the {{ job_title }} role at {{ company }}."
  closing: "Thank you for your consideration,\n\nJeff McEntarffer"

# ────────────────────────────────────────────
# Skills to match on (required by find_jobs.py)
skills:
  - Python
  - Django
  - REST

# ────────────────────────────────────────────
# (Optional) List of URLs to scrape for new jobs
# your find_jobs.py may look for this—if it does, uncomment & fill:
# job_search_urls:
#   - "https://testco.example.com/careers"
#
# And/or any other keys your find_jobs.py references.
