# ────────────────────────────────────────────
# 1) Personal Info (for generate_application.py)
applicant_name: Jeff_McEntarffer
applicant_email: jeff@example.com

# ────────────────────────────────────────────
# 2) Cover‐letter Template & Context
cover_letter_template: "templates/cover_letter.html"
cover_letter_context:
  greeting: "Hello Hiring Team,"
  opening: "I’m thrilled to apply for the {{ job_title }} role at {{ company }}."
  closing: "Thank you for your consideration,\n\nJeff McEntarffer"

# ────────────────────────────────────────────
# 3) Job‐Finding Settings (for find_jobs.py)
skills:
  - Python
  - Django
  - REST

# Minimum fraction of your skills that must appear 
# in a job posting to consider it a match (0.0–1.0)
threshold: 0.6

# List of company career‐page URLs to scrape
job_search_urls:
  - "https://example.com/careers"
  - "https://anotherco.example.org/jobs"
