# ────────────────────────────────────────────
# Who you are:
applicant_name: Jeff_McEntarffer
applicant_email: jeff@example.com

# ────────────────────────────────────────────
# Where your Jinja2 cover-letter lives:
cover_letter_template: "templates/cover_letter.html"

# ────────────────────────────────────────────
# Any static fields your template expects:
cover_letter_context:
  greeting: "Hello Hiring Team,"
  opening: "I’m thrilled to apply for the {{ job_title }} role at {{ company }}."
  closing: "Thank you for your consideration,\n\nJeff McEntarffer"
