#!/usr/bin/env bash
set -euo pipefail

# 1) Find the resume PDF in output/
RESUME_PDF=$(ls output/*_resume.pdf 2>/dev/null | head -1) || {
  echo "❌ No resume PDF named *_resume.pdf found in output/"; exit 1;
}

# Derive your key (strip path + suffix)
NAME_KEY=$(basename "$RESUME_PDF" _resume.pdf)

# 2) Prompt for email
read -p "Enter your applicant email: " APPLICANT_EMAIL
if [[ -z "$APPLICANT_EMAIL" ]]; then
  echo "❌ You must enter an email"; exit 1
fi

# 3) Overwrite config.yaml
cat > config.yaml <<CFG
# Auto-generated by fix_config.sh
applicant_name: ${NAME_KEY}
applicant_email: ${APPLICANT_EMAIL}

cover_letter_template: "templates/cover_letter.html"
cover_letter_context:
  greeting:   "Hello Hiring Team,"
  opening:    "I’m excited to apply for the {{ job_title }} role at {{ company }}."
  closing:    "Thank you for your consideration,\n\n${NAME_KEY}"

skills:
  - Python
  - Remote
threshold: 0.5
CFG

echo "✅ Generated config.yaml:"
echo "   applicant_name: ${NAME_KEY}"
echo "   applicant_email: ${APPLICANT_EMAIL}"
