name: Auto-Apply AI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (& webdriver-manager)
        run: |
          pip install selenium pyyaml requests weasyprint jinja2 webdriver-manager

      - name: Install Chromium Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Symlink Chromium so Selenium finds “google-chrome”
        run: |
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome

      - name: Debug Chrome & driver paths
        run: |
          echo "Which chromium-browser → $(which chromium-browser)"  
          ls -l /usr/bin/chromium-browser /usr/bin/google-chrome || true  

      - name: Find jobs
        run: python find_jobs.py

      - name: Run Auto-Apply
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python generate_application.py
