name: Auto-Apply AI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium pyyaml requests weasyprint jinja2

      - name: Install Google Chrome & matching ChromeDriver
        run: |
          # Add Google Chrome repo and key
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            | sudo tee /etc/apt/sources.list.d/google-chrome.list

          sudo apt-get update
          sudo apt-get install -y google-chrome-stable unzip

          # Extract major version via sed + backticks
          CHROME_VER=`google-chrome --version | sed -E 's/Google Chrome ([0-9]+)\..*/\1/'`
          echo "🔍 Detected Chrome major version $CHROME_VER"

          # Fetch the matching ChromeDriver
          DRIVER_VER=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VER`
          echo "🔍 Downloading ChromeDriver version $DRIVER_VER"
          curl -Lo /tmp/chromedriver_linux64.zip \
            "https://chromedriver.storage.googleapis.com/$DRIVER_VER/chromedriver_linux64.zip"
          unzip -o /tmp/chromedriver_linux64.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Find jobs
        run: python find_jobs.py

      - name: Run Auto-Apply
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python generate_application.py
