name: Auto-Apply AI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'   # daily at 03:00 UTC

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium pyyaml requests weasyprint jinja2

      - name: Install Chromium & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Make Selenium’s default look for "google-chrome"
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome
          # Make sure the driver is on your PATH
          sudo ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Find jobs
        run: python find_jobs.py

      - name: Run Auto-Apply
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python generate_application.py
